### PR TITLE
Submodule and README updates for AppNeta

### PR DESCRIPTION
**Pull request by fklassen**
Submodule points to appneta/dockerverth. Also updated install instructions.

### CODE REVIEW

**Comment by fklassen** [comment]
wrong fork

**Comment by riptl** [comment]
@fklassen I'm glad to see that this repo has some use. Would you mind sharing what you'd use it for
Also I have no problem pointing to another submodule if that's required.
 Thanks

**Comment by fklassen** [comment]
> @fklassen I'm glad to see that this repo has some use. Would you mind sharing what you'd use it for
> Also I have no problem pointing to another submodule if that's required.
> Thanks

@terorie thanks for checking in. We are coming to the end of a compay-wide hackathon, and we thought we may build off your work. If you go to GitHub "Network" option you can see that all we did was update the README. In the end we took a different approach.

Yes, I would be interested to see some other submodules. I find this work interesting. We have always done this stuff on bare metal machines, but it is fun to do it in Docker.

**Comment by riptl** [comment]
Really cool, thanks for sharing. I'll be sure to read up on you guys' findings. I'm still looking for a solid way to integration test a cluster of nodes in a distributed system and the solution in this repo is really hacky. Plus it's constrained to one host.

**Pull request closed without merging**
